export interface Offer {
  id: string;
  companyName: string;
  companyLogo: string;
  title: string;
  description: string;
  discount: string;
  category: string;
  expiryDate: string;
  terms: string;
  code: string;
  imageUrl: string;
  featured: boolean;
  rating: number;
  reviewCount: number;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  offerCount: number;
}

export const CATEGORIES: Category[] = [
  { id: "food", name: "Food & Dining", icon: "restaurant", color: "#FF6B4A", offerCount: 0 },
  { id: "tech", name: "Technology", icon: "laptop", color: "#3B82F6", offerCount: 0 },
  { id: "fashion", name: "Fashion", icon: "shirt", color: "#EC4899", offerCount: 0 },
  { id: "travel", name: "Travel", icon: "airplane", color: "#0D9488", offerCount: 0 },
  { id: "health", name: "Health & Fitness", icon: "fitness", color: "#10B981", offerCount: 0 },
  { id: "entertainment", name: "Entertainment", icon: "musical-notes", color: "#8B5CF6", offerCount: 0 },
  { id: "home", name: "Home & Garden", icon: "home", color: "#F59E0B", offerCount: 0 },
  { id: "beauty", name: "Beauty", icon: "sparkles", color: "#F472B6", offerCount: 0 },
];

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: "1",
    companyName: "Burger Palace",
    companyLogo: "https://ui-avatars.com/api/?name=BP&background=FF6B4A&color=fff&size=80",
    title: "Buy 1 Get 1 Free Burgers",
    description: "Enjoy our signature flame-grilled burgers with this amazing BOGO deal. Valid on all classic and premium burgers.",
    discount: "50% OFF",
    category: "food",
    expiryDate: "2026-03-15",
    terms: "Valid on dine-in orders only. Cannot be combined with other offers. One per customer per visit.",
    code: "BOGO50",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=400&fit=crop",
    featured: true,
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: "2",
    companyName: "TechWorld",
    companyLogo: "https://ui-avatars.com/api/?name=TW&background=3B82F6&color=fff&size=80",
    title: "30% Off All Laptops",
    description: "Upgrade your setup with our biggest laptop sale of the season. All brands included.",
    discount: "30% OFF",
    category: "tech",
    expiryDate: "2026-02-28",
    terms: "Valid online and in-store. While supplies last. Excludes refurbished items.",
    code: "TECH30",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=400&fit=crop",
    featured: true,
    rating: 4.5,
    reviewCount: 189,
  },
  {
    id: "3",
    companyName: "StyleHub",
    companyLogo: "https://ui-avatars.com/api/?name=SH&background=EC4899&color=fff&size=80",
    title: "Summer Collection Sale",
    description: "Get ready for summer with up to 40% off our newest arrivals. Dresses, tops, and accessories.",
    discount: "40% OFF",
    category: "fashion",
    expiryDate: "2026-04-01",
    terms: "Valid on select items. Online orders qualify for free shipping over $50.",
    code: "SUMMER40",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.6,
    reviewCount: 312,
  },
  {
    id: "4",
    companyName: "WanderLux Travel",
    companyLogo: "https://ui-avatars.com/api/?name=WL&background=0D9488&color=fff&size=80",
    title: "Weekend Getaway Packages",
    description: "Explore stunning destinations with our exclusive weekend packages. Flights and hotels included.",
    discount: "25% OFF",
    category: "travel",
    expiryDate: "2026-03-31",
    terms: "Subject to availability. Blackout dates may apply. Booking must be made 7 days in advance.",
    code: "GETAWAY25",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=400&fit=crop",
    featured: true,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "5",
    companyName: "FitLife Gym",
    companyLogo: "https://ui-avatars.com/api/?name=FL&background=10B981&color=fff&size=80",
    title: "3 Months Free Membership",
    description: "Join now and get 3 months added to your annual membership. Access to all locations and classes.",
    discount: "3 MONTHS FREE",
    category: "health",
    expiryDate: "2026-02-20",
    terms: "New members only. Annual membership required. Cancellation policy applies.",
    code: "FIT3FREE",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.3,
    reviewCount: 98,
  },
  {
    id: "6",
    companyName: "CinemaMax",
    companyLogo: "https://ui-avatars.com/api/?name=CM&background=8B5CF6&color=fff&size=80",
    title: "Movie Night Bundle",
    description: "2 tickets + large popcorn + 2 drinks for one great price. Perfect for date night.",
    discount: "$15 DEAL",
    category: "entertainment",
    expiryDate: "2026-03-10",
    terms: "Valid Monday through Thursday. Premium screens excluded. One bundle per transaction.",
    code: "MOVIE15",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.7,
    reviewCount: 445,
  },
  {
    id: "7",
    companyName: "GreenThumb",
    companyLogo: "https://ui-avatars.com/api/?name=GT&background=F59E0B&color=fff&size=80",
    title: "Spring Plant Sale",
    description: "All indoor plants 20% off. Plus free planter with purchases over $30.",
    discount: "20% OFF",
    category: "home",
    expiryDate: "2026-04-15",
    terms: "In-store only. While supplies last. Free planter limited to one per customer.",
    code: "SPRING20",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.4,
    reviewCount: 67,
  },
  {
    id: "8",
    companyName: "GlowUp Beauty",
    companyLogo: "https://ui-avatars.com/api/?name=GU&background=F472B6&color=fff&size=80",
    title: "Skincare Starter Kit",
    description: "Complete skincare routine at an unbeatable price. Cleanser, toner, moisturizer, and SPF included.",
    discount: "35% OFF",
    category: "beauty",
    expiryDate: "2026-03-20",
    terms: "Online only. One per customer. Not valid with other promotions.",
    code: "GLOW35",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=400&fit=crop",
    featured: true,
    rating: 4.8,
    reviewCount: 278,
  },
  {
    id: "9",
    companyName: "Pasta House",
    companyLogo: "https://ui-avatars.com/api/?name=PH&background=FF6B4A&color=fff&size=80",
    title: "Family Dinner Special",
    description: "Feed the whole family with our pasta combo. 2 mains, 2 sides, and dessert.",
    discount: "$29.99",
    category: "food",
    expiryDate: "2026-02-28",
    terms: "Dine-in and takeout. Valid 5PM-9PM only. Cannot combine with happy hour.",
    code: "FAMILY30",
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.6,
    reviewCount: 198,
  },
  {
    id: "10",
    companyName: "CloudTech",
    companyLogo: "https://ui-avatars.com/api/?name=CT&background=3B82F6&color=fff&size=80",
    title: "Smart Home Bundle",
    description: "Get started with smart home automation. Speaker, 2 bulbs, and hub at one great price.",
    discount: "45% OFF",
    category: "tech",
    expiryDate: "2026-03-25",
    terms: "Online only. Limited stock. Free shipping included.",
    code: "SMART45",
    imageUrl: "https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&h=400&fit=crop",
    featured: true,
    rating: 4.2,
    reviewCount: 134,
  },
  {
    id: "11",
    companyName: "RunFast Sports",
    companyLogo: "https://ui-avatars.com/api/?name=RF&background=10B981&color=fff&size=80",
    title: "Running Shoes Clearance",
    description: "Top brands at clearance prices. Nike, Adidas, New Balance and more.",
    discount: "UP TO 60% OFF",
    category: "health",
    expiryDate: "2026-02-14",
    terms: "While supplies last. No returns on clearance items. In-store and online.",
    code: "RUN60",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.5,
    reviewCount: 421,
  },
  {
    id: "12",
    companyName: "Luxe Hotels",
    companyLogo: "https://ui-avatars.com/api/?name=LH&background=0D9488&color=fff&size=80",
    title: "Spa & Stay Package",
    description: "Relax with a luxury spa treatment and overnight stay. Breakfast included.",
    discount: "$199/NIGHT",
    category: "travel",
    expiryDate: "2026-05-01",
    terms: "Subject to availability. Must book online. Non-refundable.",
    code: "SPA199",
    imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=400&fit=crop",
    featured: false,
    rating: 4.9,
    reviewCount: 87,
  },
];
